src/routes/web.php
<?php 
use Illuminate\Support\Facades\Route;

use Smertgenie\Smertinventory\Warehouse\Http\Controllers\WarehouseController;
use Smertgenie\Smertinventory\Warehouse\Http\Controllers\TagController;
use Smertgenie\Smertinventory\Warehouse\Http\Controllers\ConfigController;
//use namespace

Route::group(['middleware' => 'web'], function () {
	Route::resource('warehouses', WarehouseController::class);
	Route::get('warehouses-list', [WarehouseController::class, 'getData']);
	Route::resource('tags', TagController::class);
	Route::resource('configurations', ConfigController::class);

//Place your route here
});

src/resources/views/warehouses/create.blade.php
@extends('layouts.master')

@section('content')
<x-utilities.card>
	<x-slot name="heading">
		{{ __('Warehouse') }}
		<x-utilities.link-list href="{{route('warehouses.index')}}">{{ __('List') }}</x-utilities.link-list>
	</x-slot>
	<x-slot name="body">
		<x-alerts.errors :errors="$errors" />
		<form action="{{ route('warehouses.store') }}" method="POST">
			@csrf
			<div class="mb-3">
				<x-forms.label class="form-label" for="titleInput" :value="__('Title')" />
				<select name="parent_id" class="form-control">
					@foreach ($warehouses as $warehouse)
						<option value="{{ $warehouse->id }}">{{ $warehouse->title }}</option>
					@endforeach
				</select>
				<x-forms.error name="title" />
			</div>
			<div class="mb-3">
				<x-forms.label class="form-label" for="titleInput" :value="__('Title')" />
				<x-forms.input type="text" class="form-control" id="titleInput" name="title" :value="old('title')"
					placeholder="" />
				<x-forms.error name="title" />
			</div>
			<!-- description -->
			<div class="mb-3">
				<x-forms.label class="form-label" for="descriptionInput" :value="__('Description')" />

				<x-forms.textarea class="form-control" name="description" id="descriptionInput"
					:value="old('description')" />

				<x-forms.error name="description" />
			</div>

			<x-forms.button class="btn btn-info" type="submit">{{ __('Submit') }}</x-forms.button>
		</form>
	</x-slot>
</x-utilities.card>
@endsection

src/resources/views/warehouses/edit.blade.php
@extends('layouts.master')

@section('content')

<x-utilities.card>
	<x-slot name="heading">
		{{ __('Warehouse') }}
		<x-utilities.link-list href="{{route('warehouses.index')}}">{{ __('List') }}</x-utilities.link-list>
	</x-slot>
	<x-slot name="body">
		<x-alerts.errors :errors="$errors" />
		<form action="{{ route('warehouses.update', $warehouse->uuid) }}" method="POST">
			@csrf
			@method('PATCH')
			{{--relationalFields--}}
			<!-- title -->
			<div class="mb-3">
				<x-forms.label class="form-label" for="titleInput" :value="__('')" />

				<x-forms.input type="text" class="form-control" id="titleInput" name="title"
					:value="old('title', $warehouse->title)" placeholder="" />

				<x-forms.error name="title" />
			</div>
			<!-- description -->
			<div class="mb-3">
				<x-forms.label class="form-label" for="descriptionInput" :value="__('')" />

				<x-forms.textarea class="form-control" name="description" id="descriptionInput"
					:value="old('description', $warehouse->description)" />

				<x-forms.error name="description" />
			</div>
			<x-forms.button class="btn-primary" type="submit">{{ __('Submit') }}</x-forms.button>
		</form>
	</x-slot>
</x-utilities.card>
@endsection

src/resources/views/warehouses/index.blade.php
@extends('layouts.master')

@section('content')
<x-utilities.card>
    <x-slot name="heading">
        {{ __('Store') }}
    </x-slot>
    <x-slot name="body">
        <ul class="nav nav-sidebar w-50" data-nav-type="accordion">
            <li class="nav-item nav-item-submenu ">
                <a href="#" class="nav-link text-dark">
                    <i class="icon-tree5"></i>
                    <span id="topWarehouses"> {{ __('Warehouses') }}</span>
                </a>
                {!! $treeData !!}
            </li>
        </ul>
        <x-utilities.link-create class="float-right my-2" href="{{route('warehouses.create')}}">+ {{ __('Add New') }}
        </x-utilities.link-create>
        <x-alerts.message :message="session('success')" />
        <x-utilities.table-basic id="storeDatatable" class="display responsive nowrap" style="width:100%">
            <x-utilities.table-basic-head class="bg-info">
                <tr>
                    <th>{{ __('SL') }}</th>
                    <th>{{ __('Title') }}</th>
                    <th>{{ __('Actions' )}}</th>
                </tr>
            </x-utilities.table-basic-head>
            <x-utilities.table-basic-body>
                @foreach ($warehouses as $warehouse)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $warehouse->title }}</td>
                    <td class="d-flex justify-content-center">
                        <x-utilities.link-show href="{{route('warehouses.show', $warehouse->uuid)}}">{{ __('Show') }}
                        </x-utilities.link-show>

                        <x-utilities.link-edit href="{{route('warehouses.edit', $warehouse->uuid)}}">{{ __('Edit') }}
                        </x-utilities.link-edit>

                        <form style="display:inline" action="{{route('warehouses.destroy', $warehouse->uuid)}}"
                            method="post">
                            @csrf
                            @method('delete')
                            <x-forms.button class="btn btn-danger"
                                onClick="return confirm('Are you sure want to delete ?')" type="submit">{{ __('Delete')
                                }}</x-forms.button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </x-utilities.table-basic-body>
        </x-utilities.table-basic>
        {{ $warehouses->links('pagination::bootstrap-5') }}
    </x-slot>
</x-utilities.card>
@endsection

src/resources/views/warehouses/show.blade.php
@extends('layouts.master')

@section('content')

<x-utilities.card>
    <x-slot name="heading">
        {{ __('Warehouse') }}
        <x-utilities.link-list href="{{route('warehouses.index')}}">{{ __('List') }}</x-utilities.link-list>
    </x-slot>
    <x-slot name="body">
        <p><b>{{ __('') }} : </b> {{ $warehouse->title }}</p>
        <p><b>{{ __('') }} : </b> {{ $warehouse->description }}</p>

        {{-- @if(count($warehouse->stores))
        <h3>{{ __('Store') }}</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>{{ __('Title') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach($warehouse->stores as $store)
                <tr>
                    <td>{{ $store->store_title }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endif --}}
        {{--othersInfo--}}
    </x-slot>
</x-utilities.card>

@endsection