src/routes/web.php
<?php 
use Illuminate\Support\Facades\Route;

use Smertgenie\Smertinventory\Warehouse\Http\Controllers\WarehouseController;
use Smertgenie\Smertinventory\Warehouse\Http\Controllers\TagController;
use Smertgenie\Smertinventory\Warehouse\Http\Controllers\ConfigController;
//use namespace

Route::group(['middleware' => 'web'], function () {
	Route::resource('warehouses', WarehouseController::class);
	Route::get('warehouses-list', [WarehouseController::class, 'getData']);
	Route::resource('tags', TagController::class);
	Route::resource('configurations', ConfigController::class);

//Place your route here
});

src/Models/Tag.php
<?php

// namespace App\Models;
namespace Smertgenie\Smertinventory\Warehouse\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\QueryException;

class Tag extends Model
{
    use HasFactory;
    protected $guarded   = ['id'];

    public function getRouteKeyName()
    {
        return 'uuid';
    }
}

src/Http/Controllers/TagController.php
<?php

namespace Smertgenie\Smertinventory\Warehouse\Http\Controllers;

use Image;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use App\Http\Controllers\Controller;
use Smertgenie\Smertinventory\Warehouse\Models\Tag;
use Smertgenie\Smertinventory\Warehouse\Http\Requests\TagRequest;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $treeData = $this->getMenu($activeId = null);
        $tags = Tag::orderBy('id')->paginate(10);
        return view('smertinventory::tags.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::orderBy('id')->get();
        return view('smertinventory::tags.create', compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\TagRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagRequest $request)
    {
        try {
            
            // $tags = Tag::create(['uuid'=> Str::uuid()] + $request->all());

            $requestData = $request->all();
            $requestData['image'] = $this->uploadImage($request->file('image'));
            $product = Tag::create(['uuid'=> Str::uuid()] +$requestData);
            
            //handle relationship store
            return redirect()->route('tags.index')
                ->withSuccess(__('Successfully Created'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }

    public function uploadImage($file = null)
    {
        if (is_null($file)) return $file;
        $fileName = time() . '.' . $file->getClientOriginalExtension();
        $destinationPath = storage_path('app/public/tags/');
        $file->move($destinationPath, $fileName);
        return $fileName;     
    }

    public function show(Tag $tag)
    {
        return view('smertinventory::tags.show', compact('tag'));
    }
    public function edit(Tag $tag)
    {
        return view('smertinventory::tags.edit', compact('tag'));
    }

    public function update(TagRequest $request, Tag $tag)
    {
        try {
            // $tag->update($request->all());
            $requestData = $request->all();
            $requestData['image'] = $request->file('image') ? $this->uploadImage($request->file('image')) : $tag->image;
            $tag->update($requestData);
            //handle relationship update
            return redirect()->route('tags.index')
                ->withSuccess(__('Successfully Updated'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }
    public function destroy(Tag $tag)
    {
        try {
            $tag->delete();

            return redirect()->route('tags.index')
                ->withSuccess(__('Successfully Deleted'));
        } catch (\Exception | QueryException $e) {
            \Log::channel('pondit')->error($e->getMessage());
            return redirect()->back()->withInput()->withErrors(
                config('app.env') == 'production' ? __('Somethings Went Wrong') : $e->getMessage()
            );
        }
    }

}

src/resources/views/tags/create.blade.php
@extends('layouts.master')

@section('content')
<x-utilities.card>
	<x-slot name="heading">
		{{ __('Warehouse') }}
		<x-utilities.link-list href="{{route('tags.index')}}">{{ __('List') }}</x-utilities.link-list>
	</x-slot>
	<x-slot name="body">
	<x-alerts.errors :errors="$errors" />
		<form action="{{ route('tags.store') }}" method="POST" enctype="multipart/form-data">
			@csrf
			<!-- <div class="mb-3">
				<x-forms.label class="form-label" for="titleInput" :value="__('Title')" />
				<select name="parent_id" class="form-control">
					@foreach ($tags as $tag)
						<option value="{{ $tag->id }}">{{ $tag->title }}</option>
					@endforeach
				</select>
			</div> -->
			<div class="mb-3">
				<x-forms.label class="form-label" for="titleInput" :value="__('Title')" />
				<x-forms.input type="text" class="form-control" id="titleInput" name="title" :value="old('title')"
					placeholder="" />
				<x-forms.error name="title" />
			</div>
			<div class="mb-3">
				<x-forms.label class="form-label" for="imageInput" :value="__('Image')" />
				<x-forms.input type="file" class="form-control-file" id="imageInput" name="image" :value="old('image')"
					placeholder="" />
			</div>

			<x-forms.button class="btn btn-info" type="submit">{{ __('Submit') }}</x-forms.button>
		</form>
	</x-slot>
</x-utilities.card>
@endsection

src/resources/views/tags/edit.blade.php
@extends('layouts.master')

@section('content')

<x-utilities.card>
	<x-slot name="heading">
		{{ __('Warehouse') }}
		<x-utilities.link-list href="{{route('tags.index')}}">{{ __('List') }}</x-utilities.link-list>
	</x-slot>
	<x-slot name="body">
		
		<form action="{{ route('tags.update', $tag->uuid) }}" method="POST" enctype="multipart/form-data">
			@csrf
			@method('PATCH')
			{{--relationalFields--}}
			<!-- title -->
			<div class="mb-3">
				<x-forms.label class="form-label" for="titleInput" :value="__('')" />

				<x-forms.input type="text" class="form-control" id="titleInput" name="title"
					:value="old('title', $tag->title)" placeholder="" />

				
			</div>
			<!-- description -->
				<div class="mb-3">
				<x-forms.label class="form-label" for="imageInput" :value="__('Image')" />
				<x-forms.input type="file" class="form-control-file" id="imageInput" name="image" :value="old('image')"
					placeholder="" />
			</div>

			<x-forms.button class="btn-primary" type="submit">{{ __('Submit') }}</x-forms.button>
		</form>
	</x-slot>
</x-utilities.card>
@endsection

src/resources/views/tags/index.blade.php
@extends('layouts.master')

@section('content')
<x-utilities.card>
    <x-slot name="heading">
        {{ __('Store') }}
    </x-slot>
    <x-slot name="body">
        <ul class="nav nav-sidebar w-50" data-nav-type="accordion">
            <li class="nav-item nav-item-submenu ">
                <a href="#" class="nav-link text-dark">
                    <i class="icon-tree5"></i>
                    <span id="topWarehouses"> {{ __('Warehouses') }}</span>
                </a>
                
            </li>
        </ul>
        <x-utilities.link-create class="float-right my-2" href="{{route('tags.create')}}">+ {{ __('Add New') }}
        </x-utilities.link-create>
        <x-alerts.message :message="session('success')" />
        <x-utilities.table-basic id="storeDatatable" class="display responsive nowrap" style="width:100%">
            <x-utilities.table-basic-head class="bg-info">
                <tr>
                    <th>{{ __('SL') }}</th>
                    <th>{{ __('Title') }}</th>
                    <th>{{ __('Actions' )}}</th>
                </tr>
            </x-utilities.table-basic-head>
            <x-utilities.table-basic-body>
                @foreach ($tags as $tag)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $tag->title }}</td>
                    <td class="d-flex justify-content-center">
                        <x-utilities.link-show href="{{route('tags.show', $tag->uuid)}}">{{ __('Show') }}
                        </x-utilities.link-show>

                        <x-utilities.link-edit href="{{route('tags.edit', $tag->uuid)}}">{{ __('Edit') }}
                        </x-utilities.link-edit>

                        <form style="display:inline" action="{{route('tags.destroy', $tag->uuid)}}"
                            method="post">
                            @csrf
                            @method('delete')
                            <x-forms.button class="btn btn-danger"
                                onClick="return confirm('Are you sure want to delete ?')" type="submit">{{ __('Delete')
                                }}</x-forms.button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </x-utilities.table-basic-body>
        </x-utilities.table-basic>
        {{ $tags->links('pagination::bootstrap-5') }}
    </x-slot>
</x-utilities.card>
@endsection

src/resources/views/tags/show.blade.php
@extends('layouts.master')

@section('content')

<x-utilities.card>
    <x-slot name="heading">
        {{ __('Warehouse') }}
        <x-utilities.link-list href="{{route('tags.index')}}">{{ __('List') }}</x-utilities.link-list>
    </x-slot>
    <x-slot name="body">
        <p><b>{{ __('') }} : </b> {{ $tag->title }}</p>
        <p><b>{{ __('') }} : </b> <img src="{{ asset('storage/tags/'.$tag->image) }}" alt="{{$tag->title}} Image" height="200"></p>

        {{-- @if(count($tag->stores))
        <h3>{{ __('Store') }}</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>{{ __('Title') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach($tag->stores as $store)
                <tr>
                    <td>{{ $store->store_title }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endif --}}
        {{--othersInfo--}}
    </x-slot>
</x-utilities.card>

@endsection