src/routes/web.php
<?php 
use Illuminate\Support\Facades\Route;

use Smertgenie\Smertinventory\Warehouse\Http\Controllers\WarehouseController;
use Smertgenie\Smertinventory\Warehouse\Http\Controllers\TagController;
use Smertgenie\Smertinventory\Warehouse\Http\Controllers\ConfigController;
//use namespace

Route::group(['middleware' => 'web'], function () {
	Route::resource('warehouses', WarehouseController::class);
	Route::get('warehouses-list', [WarehouseController::class, 'getData']);
	Route::resource('tags', TagController::class);
	Route::resource('configurations', ConfigController::class);

//Place your route here
});

src/Models/Configuration.php
<?php

namespace Smertgenie\Smertinventory\Warehouse\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Configuration extends Model
{
    use HasFactory;
    protected $guarded    = ['id'];

    public function getRouteKeyName()
    {
        return 'uuid';
    }

}

src/resources/views/configurations/create.blade.php
@extends('layouts.master')

@section('content')
<x-utilities.card>
	<x-slot name="heading">
		{{ __('Warehouse') }}
		<x-utilities.link-list href="{{route('configurations.index')}}">{{ __('List') }}</x-utilities.link-list>
	</x-slot>
	<x-slot name="body">

		<form action="{{ route('configurations.store') }}" method="POST">
			@csrf

			<div class="mb-3">
				<x-forms.label class="form-label" for="titleInput" :value="__('Title')" />
				<x-forms.input type="text" class="form-control" id="titleInput" name="title" :value="old('title')"
					placeholder="" />
			</div>
			<div class="mb-3">
				<x-forms.label class="form-label" for="aliasInput" :value="__('Alias')" />
				<x-forms.input type="text" class="form-control" id="titleInput" name="alias" :value="old('alias')"
					placeholder="" />
			</div>
			<div class="mb-3">
				<x-forms.label class="form-label" for="operationInput" :value="__('Operation')" />
				<x-forms.input type="text" class="form-control" id="titleInput" name="operation" :value="old('operation')"
					placeholder="" />
			</div>
			<div class="mb-3 form-check">
				
				<x-forms.input type="checkbox" class="form-check-input" id="is_activeInput" name="is_active" value="1"
					placeholder="" />
				<x-forms.label class="form-check-label" for="is_activeInput" :value="__('Is_Active')" />
			</div>


			<x-forms.button class="btn btn-info" type="submit">{{ __('Submit') }}</x-forms.button>
		</form>
	</x-slot>
</x-utilities.card>
@endsection

src/resources/views/configurations/edit.blade.php
@extends('layouts.master')

@section('content')

<x-utilities.card>
	<x-slot name="heading">
		{{ __('Warehouse') }}
		<x-utilities.link-list href="{{route('configurations.index')}}">{{ __('List') }}</x-utilities.link-list>
	</x-slot>
	<x-slot name="body">
		
		<form action="{{ route('configurations.update', $configuration->uuid) }}" method="POST">
			@csrf
			@method('PATCH')
			{{--relationalFields--}}
			<!-- title -->
			<div class="mb-3">
				<x-forms.label class="form-label" for="titleInput" :value="__('Title')" />
				<x-forms.input type="text" class="form-control" id="titleInput" name="title" :value="old('title', $configuration->title)"
					placeholder="" />
			</div>
			<div class="mb-3">
				<x-forms.label class="form-label" for="aliasInput" :value="__('Alias')" />
				<x-forms.input type="text" class="form-control" id="titleInput" name="alias" :value="old('alias',  $configuration->alias)"
					placeholder="" />
			</div>
			<div class="mb-3">
				<x-forms.label class="form-label" for="operationInput" :value="__('Operation')" />
				<x-forms.input type="text" class="form-control" id="titleInput" name="operation" :value="old('operation',  $configuration->operation)"
					placeholder="" />
			</div>
			<div class="mb-3 form-check">
				
				<x-forms.input type="checkbox" class="form-check-input" id="is_activeInput" name="is_active" value="1"
					placeholder="" />
				<x-forms.label class="form-check-label" for="is_activeInput" :value="__('Is_Active')" />
			</div>
			<br><br>
			<x-forms.button class="btn-primary" type="submit">{{ __('Submit') }}</x-forms.button>
		</form>
	</x-slot>
</x-utilities.card>
@endsection

src/resources/views/configurations/index.blade.php
@extends('layouts.master')

@section('content')
<x-utilities.card>
    <x-slot name="heading">
        {{ __('Store') }}
    </x-slot>
    <x-slot name="body">
        <ul class="nav nav-sidebar w-50" data-nav-type="accordion">
            <li class="nav-item nav-item-submenu ">
                <a href="#" class="nav-link text-dark">
                    <i class="icon-tree5"></i>
                    <span id="topWarehouses"> {{ __('Warehouses') }}</span>
                </a>
                
            </li>
        </ul>
        <x-utilities.link-create class="float-right my-2" href="{{route('configurations.create')}}">+ {{ __('Add New') }}
        </x-utilities.link-create>
        <x-alerts.message :message="session('success')" />
        <x-utilities.table-basic id="storeDatatable" class="display responsive nowrap" style="width:100%">
            <x-utilities.table-basic-head class="bg-info">
                <tr>
                    <th>{{ __('SL') }}</th>
                    <th>{{ __('Title') }}</th>
                    <th>{{ __('Alias' )}}</th>
                    <th>{{ __('Operation' )}}</th>
                    <th>{{ __('Is Active' )}}</th>
                    <th>{{ __('Actions' )}}</th>
                </tr>
            </x-utilities.table-basic-head>
            <x-utilities.table-basic-body>
                @foreach ($configurations as $configuration)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $configuration->title }}</td>
                    <td>{{ $configuration->alias }}</td>
                    <td>{{ $configuration->operation }}</td>
                    <td>{{ $configuration->is_active }}</td>
                    <td class="d-flex justify-content-center">
                        <x-utilities.link-show href="{{route('configurations.show', $configuration->uuid)}}">{{ __('Show') }}
                        </x-utilities.link-show>

                        <x-utilities.link-edit href="{{route('configurations.edit', $configuration->uuid)}}">{{ __('Edit') }}
                        </x-utilities.link-edit>

                        <form style="display:inline" action="{{route('configurations.destroy', $configuration->uuid)}}"
                            method="post">
                            @csrf
                            @method('delete')
                            <x-forms.button class="btn btn-danger"
                                onClick="return confirm('Are you sure want to delete ?')" type="submit">{{ __('Delete')
                                }}</x-forms.button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </x-utilities.table-basic-body>
        </x-utilities.table-basic>
        {{ $configurations->links('pagination::bootstrap-5') }}
    </x-slot>
</x-utilities.card>
@endsection

src/resources/views/configurations/show.blade.php
@extends('layouts.master')

@section('content')

<x-utilities.card>
    <x-slot name="heading">
        {{ __('Warehouse') }}
        <x-utilities.link-list href="{{route('configurations.index')}}">{{ __('List') }}</x-utilities.link-list>
    </x-slot>
    <x-slot name="body">
        <p><b>{{ __('') }} : </b> {{ $configuration->title }}</p>
        <p><b>{{ __('') }} : </b> {{ $configuration->uuid }}</p>

        {{-- @if(count($tag->stores))
        <h3>{{ __('Store') }}</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>{{ __('Title') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach($tag->stores as $store)
                <tr>
                    <td>{{ $store->store_title }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endif --}}
        {{--othersInfo--}}
    </x-slot>
</x-utilities.card>

@endsection